-- Catalogo de escolas removido em 2026-08-11.
-- 188 instituicoes pre-cadastradas, TODAS sem usuario, armario ou locacao.
-- Restaurar so se voltar a fazer sentido ter o catalogo completo.

INSERT INTO schools (codigo, name, cnpj, valor_armario) VALUES
  ('etec-abz', 'Etec Adolpho Berezin', NULL, NULL),
  ('etec-ac', 'Etec Alcides Cestari', NULL, NULL),
  ('etec-ad', 'Etec Antonio Devisate', NULL, NULL),
  ('etec-ae', 'Etec Albert Einstein', NULL, NULL),
  ('etec-af', 'Etec Antônio Furlan', NULL, NULL),
  ('etec-aj', 'Etec Amim Jundi', NULL, NULL),
  ('etec-ajv', 'Etec Antônio Junqueira da Veiga', NULL, NULL),
  ('etec-amc', 'Etec Astor de Mattos Carvalho', NULL, NULL),
  ('etec-an', 'Etec Abdias do Nascimento', NULL, NULL),
  ('etec-anc', 'Etec Angelo Cavalheiro', NULL, NULL),
  ('etec-apc', 'Etec Antonio de Pádua Cardoso', NULL, NULL),
  ('etec-apch', 'Etec Arnaldo Pereira Cheregatti', NULL, NULL),
  ('etec-arac', 'Etec de Araçatuba', NULL, NULL),
  ('etec-arf', 'Etec Aristóteles Ferreira', NULL, NULL),
  ('etec-armp', 'Etec Armando Pannunzio', NULL, NULL),
  ('etec-art', 'Etec de Artes', NULL, NULL),
  ('etec-asd', 'Etec Alberto Santos Dumont', NULL, NULL),
  ('etec-ata', 'Etec Augusto Tortolero Araújo', NULL, NULL),
  ('etec-bpa', 'Etec de Bragança Paulista', NULL, NULL),
  ('etec-bs', 'Etec Benedito Storani', NULL, NULL),
  ('etec-car', 'Etec de Caraguatatuba', NULL, NULL),
  ('etec-cc', 'Etec Carlos de Campos', NULL, NULL),
  ('etec-ccs', 'Etec Carolina Carinhato Sampaio', NULL, NULL),
  ('etec-cdl', 'Etec Cidade do Livro', NULL, NULL),
  ('etec-cep', 'Etec Cepam', NULL, NULL),
  ('etec-cer', 'Etec de Cerquilho', NULL, NULL),
  ('etec-cffc', 'Etec Cel. Fernando Febeliano da Costa', NULL, NULL),
  ('etec-cjb', 'Etec Côn. José Bento', NULL, NULL),
  ('etec-cjr', 'Etec Comend. João Rays', NULL, NULL),
  ('etec-clp', 'Etec de Campo Limpo Paulista', NULL, NULL),
  ('etec-cot', 'Etec de Cotia', NULL, NULL),
  ('etec-cpc', 'Etec de Carapicuíba', NULL, NULL),
  ('etec-cra', 'Etec de Cravinhos', NULL, NULL),
  ('etec-crb', 'Etec Cel. Raphael Brandão', NULL, NULL),
  ('etec-ct', 'Etec de Cidade Tiradentes', NULL, NULL),
  ('etec-cub', 'Etec de Cubatão', NULL, NULL),
  ('etec-dacp', 'Etec Dep. Ary de Camargo Pedroso', NULL, NULL),
  ('etec-dans', 'Etec Dr. Adail Nunes da Silva', NULL, NULL),
  ('etec-dcms', 'Etec Dr. Carolino da Motta e Silva', NULL, NULL),
  ('etec-der', 'Etec Dn. Escolástica Rosa', NULL, NULL),
  ('etec-dff', 'Etec Dep. Francisco Franco', NULL, NULL),
  ('etec-dpm', 'Etec Darcy Pereira de Moraes', NULL, NULL),
  ('etec-dsb', 'Etec Dn. Sebastiana de Barros', NULL, NULL),
  ('etec-dss', 'Etec Dep. Salim Sedeh', NULL, NULL),
  ('etec-eda', 'Etec de Embu das Artes', NULL, NULL),
  ('etec-ewob', 'Etec de Esportes Curt Walter Otto Baumgart', NULL, NULL),
  ('etec-fami', 'Etec Frei Arnaldo Maria de Itaporanga', NULL, NULL),
  ('etec-fgar', 'Etec Francisco Garcia', NULL, NULL),
  ('etec-fm', 'Etec de Francisco Morato', NULL, NULL),
  ('etec-fv', 'Etec de Ferraz de Vasconcelos', NULL, NULL),
  ('etec-gmbb', 'Etec Gildo Marçal Bezerra Brandão', NULL, NULL),
  ('etec-gru', 'Etec de Guarulhos', NULL, NULL),
  ('etec-gsil', 'Etec Guaracy Silveira', NULL, NULL),
  ('etec-gtei', 'Etec Gustavo Teixeira', NULL, NULL),
  ('etec-gua', 'Etec de Guaianazes', NULL, NULL),
  ('etec-gui', 'Etec de Guaíra', NULL, NULL),
  ('etec-gvar', 'Etec Getúlio Vargas', NULL, NULL),
  ('etec-hor', 'Etec de Hortolândia', NULL, NULL),
  ('etec-hro', 'Etec de Heliópolis Arquiteto Ruy Ohtake', NULL, NULL),
  ('etec-iago', 'Etec Irmã Agostina', NULL, NULL),
  ('etec-iba', 'Etec de Ibaté', NULL, NULL),
  ('etec-ils', 'Etec de Ilha Solteira', NULL, NULL),
  ('etec-ita', 'Etec de Itanhaém', NULL, NULL),
  ('etec-itq', 'Etec de Itaquaquecetuba', NULL, NULL),
  ('etec-itq2', 'Etec Itaquera II', NULL, NULL),
  ('etec-itr', 'Etec de Itaquera', NULL, NULL),
  ('etec-itrr', 'Etec de Itararé', NULL, NULL),
  ('etec-jang', 'Etec Jd. Ângela', NULL, NULL),
  ('etec-jara', 'Etec Jaraguá', NULL, NULL),
  ('etec-jbel', 'Etec João Belarmino', NULL, NULL),
  ('etec-jdm', 'Etec Júlio de Mesquita', NULL, NULL),
  ('etec-jema', 'Etec João Elias Margutti', NULL, NULL),
  ('etec-jfa', 'Etec Joaquim Ferreira do Amaral', NULL, NULL),
  ('etec-jfsa', 'Etec Jacinto Ferreira de Sá', NULL, NULL),
  ('etec-jgar', 'Etec João Gomes de Araújo', NULL, NULL),
  ('etec-jjge', 'Etec João Jorge Geraissate', NULL, NULL),
  ('etec-jko', 'Etec Juscelino Kubitschek de Oliveira', NULL, NULL),
  ('etec-jmsi', 'Etec José Martimiano da Silva', NULL, NULL),
  ('etec-jmso', 'Etec José Miguel Soares', NULL, NULL),
  ('etec-jmst', 'Etec João Maria Stevanatto', NULL, NULL),
  ('etec-jrm', 'Etec Jorn. Roberto Marinho', NULL, NULL),
  ('etec-jrme', 'Etec José Rocha Mendes', NULL, NULL),
  ('etec-jstr', 'Etec Jorge Street', NULL, NULL),
  ('etec-laq', 'Etec Laurindo Alves de Queiroz', NULL, NULL),
  ('etec-lgom', 'Etec Lauro Gomes', NULL, NULL),
  ('etec-lin', 'Etec de Lins', NULL, NULL),
  ('etec-mai', 'Etec de Mairinque', NULL, NULL),
  ('etec-mam', 'Etec Mons. Antonio Magliano', NULL, NULL),
  ('etec-mand', 'Etec Mandaqui', NULL, NULL),
  ('etec-mass', 'Etec Machado de Assis', NULL, NULL),
  ('etec-mau', 'Etec de Mauá', NULL, NULL),
  ('etec-mlk', 'Etec Martin Luther King', NULL, NULL),
  ('etec-mm', 'Etec de Monte Mor', NULL, NULL),
  ('etec-mpo', 'Etec de Mairiporã', NULL, NULL),
  ('etec-mra', 'Etec Manoel dos Reis Araújo', NULL, NULL),
  ('etec-orq', 'Etec Orlando Quagliato', NULL, NULL),
  ('etec-paam', 'Etec Prof. Adolpho Arruda Mello', NULL, NULL),
  ('etec-pabg', 'Etec Prof. André Bogasian', NULL, NULL),
  ('etec-pabh', 'Etec Prof. Adhemar Batista Heméritas', NULL, NULL),
  ('etec-pabs', 'Etec Prof. Alfredo de Barros Santos', NULL, NULL),
  ('etec-pabsi', 'Etec Prof. Armando Bayeux da Silva', NULL, NULL),
  ('etec-paf', 'Etec Pref. Alberto Feres', NULL, NULL),
  ('etec-pag', 'Etec Prof. Aprígio Gonzaga', NULL, NULL),
  ('etec-pajf', 'Etec Prof. Armando José Farinazzo', NULL, NULL),
  ('etec-pam', 'Etec Polivalente de Americana', NULL, NULL),
  ('etec-paof', 'Etec Profª Anna de Oliveira Ferraz', NULL, NULL),
  ('etec-pasp', 'Etec Prof. Alcídio de Souza Prado', NULL, NULL),
  ('etec-pbad', 'Etec Pedro Badran', NULL, NULL),
  ('etec-pbel', 'Etec Pq. Belém', NULL, NULL),
  ('etec-pbg', 'Etec Prof. Basilides de Godoy', NULL, NULL),
  ('etec-pbot', 'Etec Paulino Botelho', NULL, NULL),
  ('etec-pbp', 'Etec Pref. Braz Paschoalin', NULL, NULL),
  ('etec-pca', 'Etec Prof. Camargo Aranha', NULL, NULL),
  ('etec-pcb', 'Etec Prof. Carmelina Barbosa', NULL, NULL),
  ('etec-pcbt', 'Etec Prof. Carmine Biagio Tundisi', NULL, NULL),
  ('etec-pccj', 'Etec Prof. Carmelino Corrêa Júnior', NULL, NULL),
  ('etec-pcls', 'Etec Pe. Carlos Leôncio da Silva', NULL, NULL),
  ('etec-pcm', 'Etec Paulo do Carmo Monteiro', NULL, NULL),
  ('etec-pdaet', 'Etec Prof. Dr. Antônio Eufrásio de Toledo', NULL, NULL),
  ('etec-pdan', 'Etec Pedro D''Arcádia Neto', NULL, NULL),
  ('etec-pdjd', 'Etec Prof. Dr. José Dagnoni', NULL, NULL),
  ('etec-pdqkt', 'Etec Prof. Dra. Doroti Quiomi Kanashiro Toyohara', NULL, NULL),
  ('etec-peg', 'Etec Prof. Edson Galvão', NULL, NULL),
  ('etec-pegt', 'Etec Prof. Ermelinda Giannini Teixeira', NULL, NULL),
  ('etec-pelv', 'Etec Prof. Eudécio Luiz Vicente', NULL, NULL),
  ('etec-per', 'Etec de Peruíbe', NULL, NULL),
  ('etec-pfa', 'Etec Pedro Ferreira Alves', NULL, NULL),
  ('etec-pfm', 'Etec Prof. Fausto Mazzola', NULL, NULL),
  ('etec-pfs', 'Etec Prof. Francisco dos Santos', NULL, NULL),
  ('etec-pg', 'Etec de Praia Grande', NULL, NULL),
  ('etec-pgn', 'Etec Philadelpho Gouvea Netto', NULL, NULL),
  ('etec-phas', 'Etec Prof. Horácio Augusto da Silveira', NULL, NULL),
  ('etec-phma', 'Etec Prof. Helcy Moreira Martins Aguiar', NULL, NULL),
  ('etec-pie', 'Etec de Piedade', NULL, NULL),
  ('etec-pinp', 'Etec Prof. Ilza Nascimento Pintus', NULL, NULL),
  ('etec-piz', 'Etec Prof. Idio Zucchi', NULL, NULL),
  ('etec-pjcs', 'Etec Prof. José Carlos Seno Júnior', NULL, NULL),
  ('etec-pjia', 'Etec Prof. José Ignácio Azevedo Filho', NULL, NULL),
  ('etec-pjnd', 'Etec Pe. José Nunes Dias', NULL, NULL),
  ('etec-pjs', 'Etec Prof. Jadyr Salles', NULL, NULL),
  ('etec-pjsc', 'Etec Prof. José Sant''Ana de Castro', NULL, NULL),
  ('etec-pjuv', 'Etec Pq. da Juventude', NULL, NULL),
  ('etec-plmm', 'Etec Prof. Luzia Maria Machado', NULL, NULL),
  ('etec-plpb', 'Etec Prof. Luiz Pires Barbosa', NULL, NULL),
  ('etec-pmav', 'Etec Prof. Mário Antônio Verza', NULL, NULL),
  ('etec-pmcm', 'Etec Prof. Maria Cristina Medeiros', NULL, NULL),
  ('etec-pmg', 'Etec Prof. Milton Gazzetti', NULL, NULL),
  ('etec-pmk', 'Etec Prof. Massuyuki Kawano', NULL, NULL),
  ('etec-pmla', 'Etec Prof. Matheus Leite de Abreu', NULL, NULL),
  ('etec-pmtf', 'Etec Prof. Marinês Teodoro de Freitas Almeida', NULL, NULL),
  ('etec-pmusp', 'Etec Prof. Marcos Uchôas dos Santos Penchel', NULL, NULL),
  ('etec-pnlr', 'Etec Prof. Nair Luccas Ribeiro', NULL, NULL),
  ('etec-pplbs', 'Etec Prof. Pedro Leme Brisolla Sobrinho', NULL, NULL),
  ('etec-ptms', 'Etec Prof. Terezinha Monteiro dos Santos', NULL, NULL),
  ('etec-puf', 'Etec Prof. Urias Ferreira', NULL, NULL),
  ('etec-pvg', 'Etec Pres. Vargas', NULL, NULL),
  ('etec-rda', 'Etec Rodrigues de Abreu', NULL, NULL),
  ('etec-reg', 'Etec de Registro', NULL, NULL),
  ('etec-rfs', 'Etec Rubens de Faria e Souza', NULL, NULL),
  ('etec-rjdg', 'Etec Rodolpho José Del Guerra', NULL, NULL),
  ('etec-rps', 'Etec Rosa Perrone Scavone', NULL, NULL),
  ('etec-rt', 'Etec Raposo Tavares', NULL, NULL),
  ('etec-sam', 'Etec Sebastiana Augusta de Moraes', NULL, NULL),
  ('etec-sap', 'Etec de Sapopemba', NULL, NULL),
  ('etec-sfs', 'Etec de Sta. Fé do Sul', NULL, NULL),
  ('etec-sg', 'Etec Sales Gomes', NULL, NULL),
  ('etec-si', 'Etec de Sta. Isabel', NULL, NULL),
  ('etec-sif', 'Etec Sta. Ifigenia', NULL, NULL),
  ('etec-sm', 'Etec São Mateus', NULL, NULL),
  ('etec-smc', 'Etec Sylvio de Mattos Carvalho', NULL, NULL),
  ('etec-sp', 'Etec de São Paulo', NULL, NULL),
  ('etec-srv', 'Etec de Sta. Rosa de Viterbo', NULL, NULL),
  ('etec-ss', 'Etec de São Sebastião', NULL, NULL),
  ('etec-suz', 'Etec de Suzano', NULL, NULL),
  ('etec-tacno', 'Etec Tereza Aparecida Cardoso Nunes de Oliveira', NULL, NULL),
  ('etec-tagk', 'Etec Ten. Av. Gustavo Klug', NULL, NULL),
  ('etec-tc', 'Etec Trajano Camargo', NULL, NULL),
  ('etec-tds', 'Etec de Taboão da Serra', NULL, NULL),
  ('etec-tiq', 'Etec de Tiquatira', NULL, NULL),
  ('etec-tm', 'Etec Takashi Morita', NULL, NULL),
  ('etec-uir', 'Etec Uirapuru', NULL, NULL),
  ('etec-vav', 'Etec Vasco Antonio Venchiarutti', NULL, NULL),
  ('etec-vf', 'Etec de Vila Formosa', NULL, NULL),
  ('etec-vgs', 'Etec de Vargem Grande do Sul', NULL, NULL),
  ('etec-vvam', 'Etec Vereador Valdivino Antônio Marcusso', NULL, NULL),
  ('etec-vvsf', 'Etec Ver. e Vice Pref. Sérgio da Fonseca', NULL, NULL),
  ('etec-wdj', 'Etec Waldir Duron Junior', NULL, NULL),
  ('etec-zl', 'Etec da Zona Leste', NULL, NULL)
ON CONFLICT (codigo) DO NOTHING;
